export const mockProducts = [
  {
    id: "mock-1",
    product_code: "USBC-1M-BLK-001",
    name: "USB-C 고속충전 케이블 1m 블랙",
    category_name: "충전 케이블",
    supplier_name: "기본 공급처",
    connector_type: "USB-C",
    cable_length: "1m",
    color: "블랙",
    current_stock: 18,
    safety_stock: 10,
    sale_price: 8000,
    status: "판매중",
    display_location: "A-1 진열대",
  },
  {
    id: "mock-2",
    product_code: "LTG-2M-WHT-001",
    name: "라이트닝 케이블 2m 화이트",
    category_name: "충전 케이블",
    supplier_name: "기본 공급처",
    connector_type: "Lightning",
    cable_length: "2m",
    color: "화이트",
    current_stock: 4,
    safety_stock: 8,
    sale_price: 10000,
    status: "발주필요",
    display_location: "A-2 진열대",
  },
  {
    id: "mock-3",
    product_code: "HDMI-3M-BLK-001",
    name: "HDMI 2.0 케이블 3m 블랙",
    category_name: "영상 케이블",
    supplier_name: "영상케이블 도매",
    connector_type: "HDMI",
    cable_length: "3m",
    color: "블랙",
    current_stock: 0,
    safety_stock: 5,
    sale_price: 12000,
    status: "품절",
    display_location: "B-1 진열대",
  },
  {
    id: "mock-4",
    product_code: "LAN-CAT6-5M-001",
    name: "CAT6 랜 케이블 5m",
    category_name: "네트워크 케이블",
    supplier_name: "네트워크 자재몰",
    connector_type: "LAN",
    cable_length: "5m",
    color: "블루",
    current_stock: 11,
    safety_stock: 10,
    sale_price: 9000,
    status: "판매중",
    display_location: "C-1 진열대",
  },
];

export const mockDailyTasks = [
  { type: "오픈", text: "POS/카드단말기 정상 작동 확인", checked: true },
  { type: "오픈", text: "C타입 1m/2m 인기 상품 진열 보충", checked: true },
  { type: "영업중", text: "고객이 자주 찾은 상품 메모", checked: false },
  { type: "마감", text: "품절/부족 상품과 발주 필요 상품 기록", checked: false },
];

export const mockSalesSummary = {
  total_sales_amount: 248000,
  total_sales_quantity: 31,
  sales_count: 19,
};
